### PR TITLE
srt subtitles file saving and source mute detection

### PR DESCRIPTION
**Pull request by royshil**

### CODE REVIEW

**Comment by royshil** [comment]
@umireon are you able to test this quick and approve? 🙏

**Comment by umireon** [comment]
@royshil Can you add the Seeking Testers label?

**Comment by royshil** [comment]
@umireon i added but the label doesn't affect CI right now in this project, I believe

**Comment by umireon** [comment]
I will make a PR containing various fixes for CI pipelines first. This will include the fix to have the Seeking Testers label work.

**Comment by umireon** [comment]
Opened #37

**Comment by umireon** [comment]
@royshil Can you update this branch to master?

**Pull request merged**
